### ISSUE TITLE
TypeError: sum() got an unexpected keyword argument 'keepdim'

### ISSUE THREAD

**Issue by AI-liu** [timomernick/pytorch-capsule#3]
I get a error:
  File "/home/ai/pytorch-capsule-master/capsule_layer.py", line 53, in squash
    mag_sq = torch.sum(s**2, dim=2, keepdim=True)
TypeError: sum() got an unexpected keyword argument 'keepdim'

how to fix this?
pip install torch-version?

thanks！

**Comment by AlexHex7** [comment]
What's the version of pytorch you use? Try update pytorch?
https://github.com/pytorch/pytorch/issues/1597

The version of pytorch I use is 0.2

**Comment by timomernick** [comment]
I don't get this error (obviously) and I'm on pytorch 0.2.0.post3.  Anyone else?

**Comment by timomernick** [comment]
I'm going to close this because nobody else has reported it and I think it's from before all the broadcasting etc. changes in Pytorch 0.2
