### ISSUE TITLE
Type Invalid Error

### ISSUE THREAD

**Issue by yellowtownhz** [timomernick/pytorch-capsule#5]
Hi,
I tried to run ur code, i got an error, do u know how to fix this?
thx~ :)

Here is the Traceback Information:
yellowtown@Yellowtown:/media/yellowtown/Work/Github/pytorch-capsule$ python3.5 main.py 
Traceback (most recent call last):
  File "main.py", line 61, in <module>
    output_unit_size=output_unit_size).cuda()
  File "/media/yellowtown/Work/Github/pytorch-capsule/capsule_network.py", line 53, in __init__
    self.reconstruct0 = nn.Linear(num_output_units*output_unit_size, (reconstruction_size * 2) / 3)
  File "/home/yellowtown/.local/lib/python3.5/site-packages/torch/nn/modules/linear.py", line 39, in __init__
    self.weight = Parameter(torch.Tensor(out_features, in_features))
TypeError: torch.FloatTensor constructor received an invalid combination of arguments - got (float, int), but expected one of:
 * no arguments
 * (int ...)
      didn't match because some of the arguments have invalid types: (float, int)
 * (torch.FloatTensor viewed_tensor)
 * (torch.Size size)
 * (torch.FloatStorage data)
 * (Sequence data)

**Comment by timomernick** [comment]
Is this a problem only in Python 3.5?  I use 2.7.  I can check later on a different machine, but can you try casting to int explicitly like this?

```(reconstruction_size * 2) / 3)```

to

```int(reconstruction_size * 2) / 3))```

**Comment by timomernick** [comment]
Confirmed this is python3 int/float stuff, fixed in b193a4c834b3e2d52f29d1d141dce681c7e61b7e

**Comment by yellowtownhz** [comment]
it works!~ 
thank u so much~ :)
